### ISSUE TITLE
Manifest entry record may not have CSS field

### ISSUE THREAD

**Issue by mattste** [mindreframer/vite_phx#1]
I am running into an error because `cssfiles` is set to `nil` in the `Entry` struct.

Here is the example manifest.json entry:
```
"entryname": {
    "file": "assets/script.hash.js",
    "src": "script.ts",
    "isEntry": true,
    "imports": [
    ]
  }
```

According to [Vite's manifest plugin](https://github.com/vitejs/vite/blob/main/packages/vite/src/node/plugins/manifest.ts#L14), the `css` field is optional and Vite is behaving as expected. My suggested fix is to set a default [on this line](https://github.com/mindreframer/vite_phx/blob/8b84143fd4738ee5f62734fadcac0e41b88c8ce8/lib/vite/manifest.ex#L49).

Thank you so much for the excellent library and blog posts! It's helped smooth my team's transition to Vite.

**Comment by mindreframer** [comment]
Hey @mattste, glad to hear that this package was helpful! You are right, CSS could be empty and setting a default should be a quick fix.
