### ISSUE TITLE
[Bug] ManifestReader does not crash on missing file

### ISSUE THREAD

**Issue by joeppeeters** [mindreframer/vite_phx#7]
### Description

Currently the Manifest reader [logs an error](https://github.com/mindreframer/vite_phx/blob/a3de00bf6b07fadb35f94c57b4195393d1080dda/lib/vite/manifest_reader.ex#L26-L30) when the file is not found. However, it doesn't crash. Because of that it returns `:ok` from the logger function and stores that in the `Cache`.

Upon reading the cache it breaks with a `Protocol.UndefinedError - protocol Enumerable not implemented for :ok of type Atom. ` This is really cryptic for what actually is happening.

### Proposal 

Replace the call to Logger with raising an exception. This allows you to keep the log line and the error together and makes it more clear what is wrong.

### Suggestions

```elixir
defmodule Vite.ManifestReader.MissingManifestFileError do
  defexception [:manifest_file]
   
  @impl true
  def message(exception) do
     """
     Could not find static manifest at "#{inspect(exception.manifest_file)}". 
          Run "mix phx.digest" after building your static files
          or remove the configuration from "config/prod.exs".
     """
  end
end
```

```elixir
  # manifest_reader.ex
  if File.exists!(...) do
    ..
  else
    raise MissingManifestFileError, manifest_file: full_vite_manifest
  end
```

**Comment by mindreframer** [comment]
Hey @joeppeeters, thanks for the proposal! 

Feel free to open a PR, I will then cut a new release.
